/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package digitaldiary;

import java.io.BufferedWriter;
import java.io.FileWriter;
import javax.swing.JOptionPane;

/**
 *
 * @author aks
 */
public class CalendarOptions extends javax.swing.JFrame {
private int selectedOperation=0;
    /**
     * Creates new form CalendarOptions
     */
    public CalendarOptions() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        optionButtonGroup = new javax.swing.ButtonGroup();
        labelSelectedDate = new javax.swing.JLabel();
        dateLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        selectOperation = new javax.swing.JLabel();
        addNoteRB = new javax.swing.JRadioButton();
        deleteNoteRB = new javax.swing.JRadioButton();
        viewNotesRB = new javax.swing.JRadioButton();
        specialDayRB = new javax.swing.JRadioButton();
        btnOkay = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("What do you want to do ?");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        labelSelectedDate.setFont(new java.awt.Font("Cantarell", 1, 17)); // NOI18N
        labelSelectedDate.setText("Selecetd Date :");

        selectOperation.setFont(new java.awt.Font("Cantarell", 1, 17)); // NOI18N
        selectOperation.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        selectOperation.setText("Select an operation");

        optionButtonGroup.add(addNoteRB);
        addNoteRB.setText("Add a Note");

        optionButtonGroup.add(deleteNoteRB);
        deleteNoteRB.setText("Delete Notes");

        optionButtonGroup.add(viewNotesRB);
        viewNotesRB.setText("View Notes");

        optionButtonGroup.add(specialDayRB);
        specialDayRB.setText("Add a special day/Event");

        btnOkay.setText("Okay");
        btnOkay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkayActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(labelSelectedDate, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(selectOperation, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(viewNotesRB)
                            .addComponent(addNoteRB))
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(specialDayRB)
                            .addComponent(deleteNoteRB)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(btnOkay, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelSelectedDate, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(selectOperation, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteNoteRB)
                    .addComponent(viewNotesRB))
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(specialDayRB)
                    .addComponent(addNoteRB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(btnOkay)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        labelSelectedDate.setText(CalUI.selectedDate+" - "+CalUI.selectedMonth+" - "+CalUI.selectedYear);
        viewNotesRB.setSelected(true); 
    }//GEN-LAST:event_formWindowOpened

    private void btnOkayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkayActionPerformed
       if(viewNotesRB.isSelected())
           selectedOperation=1;
       else if(deleteNoteRB.isSelected())
           selectedOperation=2;
       else if(addNoteRB.isSelected())
           selectedOperation=3;
       else if(specialDayRB.isSelected())
           selectedOperation=4;
        
       switch(selectedOperation)
       {
           case 1:
                { //View Notes
                    ViewAll va=new ViewAll();
                    va.setVisible(true);
                 
                break;
                }
           case 2: // Delete notes
                DeleteNote dn = new DeleteNote();
                dn.setVisible(true);
                this.dispose();
                break;
           case 3: 
                {
                    NoteMaker.lblSelectedDate.setText(CalUI.selectedDate+"-"+CalUI.selectedMonth+"-"+CalUI.selectedYear);
                    this.dispose();
                    break;
                }
              
           case 4: 
                {
                    String special=JOptionPane.showInputDialog("Enter Description");
                    if(special!=null && !special.isEmpty())
                    {
                        try
                        {
                            BufferedWriter bw=new BufferedWriter(new FileWriter("specialEventsLog.dat", true));
                            bw.append(special+"# "+CalUI.selectedDate+" * "+CalUI.selectedMonth+" ~ "+CalUI.selectedYear+"\n");
                            bw.close();
                            JOptionPane.showMessageDialog(null,"Special Day added");
                        }
                        catch(Exception e)
                        {
                            e.printStackTrace();
                        }
                    }
                    break;
                }
               
           default:JOptionPane.showMessageDialog(null, "Select An option");
       }
    }//GEN-LAST:event_btnOkayActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalendarOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalendarOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalendarOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalendarOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalendarOptions().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton addNoteRB;
    private javax.swing.JButton btnOkay;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JRadioButton deleteNoteRB;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labelSelectedDate;
    private javax.swing.ButtonGroup optionButtonGroup;
    private javax.swing.JLabel selectOperation;
    private javax.swing.JRadioButton specialDayRB;
    private javax.swing.JRadioButton viewNotesRB;
    // End of variables declaration//GEN-END:variables
}
