/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package digitaldiary;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import javax.swing.DefaultListModel;

/**
 *
 * @author aks
 */
public class ViewToday extends javax.swing.JFrame {

    /**
     * Creates new form ViewToday
     */
    public ViewToday() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listNotes = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        listSpecial = new javax.swing.JList<>();
        dateLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        listNotes.setModel(new DefaultListModel());
        jScrollPane1.setViewportView(listNotes);

        listSpecial.setModel(new DefaultListModel());
        jScrollPane2.setViewportView(listSpecial);

        dateLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(dateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(dateLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
       dateLabel.setText(CalUI.realDay+" - "+CalUI.realMonth+" - "+CalUI.realYear);
       
       DefaultListModel dn=(DefaultListModel)listNotes.getModel();
       DefaultListModel ds=(DefaultListModel)listSpecial.getModel();
        
        
        
        try
        {
            if((new File("allNotesLog.dat")).exists())
            {
                BufferedReader br = new BufferedReader(new FileReader("allNotesLog.dat"));
                String s="";
                String date, month, year;
                while((s=br.readLine())!=null)
                {
                    date=s.substring(s.lastIndexOf("@")+1, s.lastIndexOf("-")).trim();
                    month=s.substring(s.lastIndexOf("-")+1, s.lastIndexOf("_")).trim();
                    year=s.substring(s.lastIndexOf("_")+1,s.lastIndexOf(".")).trim();
                    int d=Integer.parseInt(date);
                    int m=Integer.parseInt(month);
                    int y=Integer.parseInt(year);
                    if(d==CalUI.realDay && m==CalUI.realMonth && y==CalUI.realYear)
                    dn.addElement(s);
                }
                br.close();
            }
            if((new File("specialEventsLog.dat")).exists())
            {
                BufferedReader b = new BufferedReader(new FileReader("specialEventsLog.dat"));
                String str="";
                while((str=b.readLine())!=null)
                {
                    String date=str.substring(str.lastIndexOf("#")+1, str.lastIndexOf("*")).trim();
                    String month=str.substring(str.lastIndexOf("*")+1, str.lastIndexOf("~")).trim();
                    String year=str.substring(str.lastIndexOf("~")+1).trim();
                    int d=Integer.parseInt(date);
                    int m=Integer.parseInt(month);
                    int y=Integer.parseInt(year);
                    if(d==CalUI.realDay && m==CalUI.realMonth+1 && y==CalUI.realYear)
                    ds.addElement(str.substring(0,str.lastIndexOf("#")));
                }
                b.close();
            }
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewToday.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewToday.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewToday.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewToday.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewToday().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dateLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> listNotes;
    private javax.swing.JList<String> listSpecial;
    // End of variables declaration//GEN-END:variables
}
